LOCATIONS_FILE = "locations.json"
BACKUP_LOCATIONS_FILE = "backup/locations.json"
CURRENT_SCENE_FILE = "current_scene.json"

TRACKER_ITEMS = [
    "deku stick upgrade (oot)",
    "deku nut upgrade (oot)",
    "bomb bag (oot)",
    "fairy bow (oot)",
    "fire arrows (oot)",
    "din's fire (oot)",
    "kokiri sword (oot)",
    "deku shield (oot)",

    "fairy slingshot (oot)",
    "ocarina (oot)",
    "bombchu bag (oot)",
    "hookshot (oot)",
    "ice arrows (oot)",
    "farore's wind (oot)",
    "master sword (oot)",
    "hylian shield (oot)",

    "boomerang (oot)",
    "lens of truth (oot)",
    "magic beans (oot)",
    "megaton hammer (oot)",
    "light arrows (oot)",
    "nayru's love (oot)",
    "biggoron's sword (oot)",
    "mirror shield (oot)",

    "zelda's lullaby (oot)",
    "epona's song (oot)",
    "saria's song (oot)",
    "sun's song (oot)",
    "song of time (oot)",
    "song of storms (oot)",
    "iron boots (oot)",
    "hover boots (oot)",

    "minuet of forest (oot)",
    "bolero of fire (oot)",
    "serenade of water (oot)",
    "requiem of spirit (oot)",
    "nocturne of shadow (oot)",
    "prelude of light (oot)",
    "goron tunic (oot)",
    "zora tunic (oot)",

    "ruto's letter (oot)",
    "empty bottle (oot) 2",
    "empty bottle (oot) 3",
    "empty bottle (oot) 4",
    "progressive scale (oot)",
    "magic upgrade (oot)",
    "progressive strength (oot)",
    "progressive wallet (oot)",

    "gold skulltula tokens (oot)",
    "stone of agony (oot)",
    "gerudo's membership card (oot)",
    "keaton mask (oot)",
    "skull mask (oot)",
    "spooky mask (oot)",
    "bunny hood (oot)",
    "mask of truth (oot)",

    "pocket egg (oot)",
    "zelda's letter (oot)",
    "pocket cucco (oot)",
    "cojiro (oot)",
    "odd mushroom (oot)",
    "odd potion (oot)",
    "small key (bottom of the well) (oot)",
    "small key (gerudo's training ground) (oot)",

    "poacher's saw (oot)",
    "broken goron's sword (oot)",
    "prescription (oot)",
    "eyeball frog (oot)",
    "eye drops (oot)",
    "claim check (oot)",
    "key ring (hideout) (oot)",
    "small key (ganon's castle) (oot)",

    "kokiri's emerald (oot)",
    "forest medallion (oot)",
    "fire medallion (oot)",
    "water medallion (oot)",
    "spirit medallion (oot)",
    "shadow medallion (oot)",
    "light medallion (oot)",
    "empty",
  
  
    "goron's ruby (oot)",
    "small key (forest temple) (oot)",
    "small key (fire temple) (oot)",
    "small key (water temple) (oot)",
    "small key (spirit temple) (oot)",
    "small key (shadow temple) (oot)",
    "empty",
    "empty",


    "zora's sapphire (oot)",
    "boss key (forest temple) (oot)",
    "boss key (fire temple) (oot)",
    "boss key (water temple) (oot)",
    "boss key (spirit temple) (oot)",
    "boss key (shadow temple) (oot)",
    "empty",
    "empty",

    # Majoras Mask
    "ocarina (mm)",
    "hero's bow (mm)",
    "fire arrows (mm)",
    "ice arrows (mm)",
    "light arrows (mm)",
    "progressive sword (mm)",
    "hero's shield (mm)",
    "mirror shield (mm)",

    "bomb bag (mm)",
    "bombchu bag (mm)",
    "deku stick upgrade (mm)",
    "deku nut upgrade (mm)",
    "magic bean (mm)",
    "bottle of gold dust (mm)",
    "empty bottle (mm) 2",
    "empty bottle (mm) 3",

    "powder keg (mm)",
    "pictograph box (mm)",
    "lens of truth (mm)",
    "hookshot (mm)",
    "great fairy's sword (mm)",
    "empty bottle (mm) 4",
    "empty bottle (mm) 5",
    "empty bottle (mm) 6",

    "song of time (mm)",
    "song of healing (mm)",
    "epona's song (mm)",
    "song of soaring (mm)",
    "song of storms (mm)",
    "progressive wallet (mm)",
    "magic upgrade (mm)",
    "moon's tear (mm)",

    "sonata of awakening (mm)",
    "progressive goron lullaby (mm)",
    "new wave bossa nova (mm)",
    "elegy of emptiness (mm)",
    "oath to order (mm)",
    "stray fairy (clock town) (mm)",
    "room key (mm)",
    "land title deed (mm)",

    "postman's hat (mm)",
    "all-night mask (mm)",
    "blast mask (mm)",
    "stone mask (mm)",
    "great fairy's mask (mm)",
    "deku mask (mm)",
    "pendant of memories (mm)",
    "swamp title deed (mm)",

    "keaton mask (mm)",
    "bremen mask (mm)",
    "bunny hood (mm)",
    "don gero's mask (mm)",
    "mask of scents (mm)",
    "goron mask (mm)",
    "letter to kafei (mm)",
    "mountain title deed (mm)",

    "romani's mask (mm)",
    "circus leader's mask (mm)",
    "kafei's mask (mm)",
    "couple's mask (mm)",
    "mask of truth (mm)",
    "zora mask (mm)",
    "letter to mama (mm)",
    "ocean title deed (mm)",

    "kamaro's mask (mm)",
    "gibdo mask (mm)",
    "garo's mask (mm)",
    "captain's hat (mm)",
    "giant's mask (mm)",
    "fierce deity's mask (mm)",
    "swamp skulltula token (mm)",
    "ocean skulltula token (mm)",

    "odolwa's remains (mm)",
    "stray fairy (woodfall temple) (mm)",
    "goht's remains (mm)",
    "stray fairy (snowhead temple) (mm)",
    "gyorg's remains (mm)",
    "stray fairy (great bay temple) (mm)",
    "twinmold's remains (mm)",
    "stray fairy (stone tower temple) (mm)",

    "small key (woodfall temple) (mm)",
    "boss key (woodfall temple) (mm)",
    "small key (snowhead temple) (mm)",
    "boss key (snowhead temple) (mm)",
    "small key (great bay temple) (mm)",
    "boss key (great bay temple) (mm)",
    "small key (stone tower temple) (mm)",
    "boss key (stone tower temple) (mm)",




]

DUNGEON_ENTRANCES = [""
    "Deku Tree",
    "Dodongo's Cavern",
    "Jabu-Jabu's Belly",
    "Forest Temple",
    "Fire Temple",
    "Water Temple",
    "Shadow Temple",
    "Spirit Temple",
    "Bottom of the Well",
    "Ice Cavern",
    "Gerudo's Training Ground",
    "Woodfall Temple",
    "Great Bay Temple",
    "Snowhead Temple",
    "Stone Tower Temple",
    "Inverted Stone Tower Temple",
    "Beneath The Well Canyon",
    "Beneath The Well Ikana Castle",
    "Secret Shrine",
    "Ikana Castle",
    "Swamp Spider House",
    "Ocean Spider House",
    "Clock Tower Roof",
    "Ganon's Castle",
    "Beneath The Well", #Placeholder
]

BOSS_ENTRANCES = LAIRS = [
    "Gohma's Lair",
    "King Dodongo's Lair",
    "Barinade's Lair",
    "Phantom Ganon's Lair",
    "Volvagia's Lair",
    "Morpha's Lair",
    "Twinrova's Lair & Nabooru's Mini-Boss Room",
    "Bongo Bongo's Lair",
    #"Ganondorf's Lair",
    #"Majora's Lair",
    "Odolwa's Lair",
    "Twinmold's Lair",
    "Goht's Lair",
    #"Igos du Ikana's Lair",
    "Gyorg's Lair",
]

# Memory to string table for location in Ocarina of Time
SCENE_DIC_OOT = {
    "0x0000": "Inside the Deku Tree",
    "0x0001": "Dodongo's Cavern",
    "0x0002": "Inside Jabu-Jabu's Belly",
    "0x0003": "Forest Temple",
    "0x0004": "Fire Temple",
    "0x0005": "Water Temple",
    "0x0006": "Spirit Temple",
    "0x0007": "Shadow Temple",
    "0x0008": "Bottom of the Well",
    "0x0009": "Ice Cavern",
    "0x000a": "Ganon's Tower",
    "0x000b": "Gerudo Training Ground",
    "0x000c": "Thieves' Hideout",
    "0x000d": "Inside Ganon's Castle",
    "0x000e": "Ganon's Tower (Collapsing)",
    "0x000f": "Inside Ganon's Castle (Collapsing)",
    "0x0010": "Treasure Box Shop",
    "0x0011": "Gohma's Lair",
    "0x0012": "King Dodongo's Lair",
    "0x0013": "Barinade's Lair",
    "0x0014": "Phantom Ganon's Lair",
    "0x0015": "Volvagia's Lair",
    "0x0016": "Morpha's Lair",
    "0x0017": "Twinrova's Lair & Nabooru's Mini-Boss Room",
    "0x0018": "Bongo Bongo's Lair",
    "0x0019": "Ganondorf's Lair",
    "0x001a": "Tower Collapse Exterior",
    "0x001b": "Market Entrance (Child - Day)",
    "0x001c": "Market Entrance (Child - Night)",
    "0x001d": "Market Entrance (Ruins)",
    "0x001e": "Back Alley (Child - Day)",
    "0x001f": "Back Alley (Child - Night)",
    "0x0020": "Market (Child - Day)",
    "0x0021": "Market (Child - Night)",
    "0x0022": "Market (Ruins)",
    "0x0023": "Temple of Time Exterior (Child - Day)",
    "0x0024": "Temple of Time Exterior (Child - Night)",
    "0x0025": "Temple of Time Exterior (Ruins)",
    "0x0026": "Know-It-All Brothers' House",
    "0x0027": "House of Twins",
    "0x0028": "Mido's House",
    "0x0029": "Saria's House",
    "0x002a": "Carpenter Boss's House",
    "0x002b": "Back Alley House (Man in Green)",
    "0x002c": "Bazaar",
    "0x002d": "Kokiri Shop",
    "0x002e": "Goron Shop",
    "0x002f": "Zora Shop",
    "0x0030": "Kakariko Potion Shop",
    "0x0031": "Market Potion Shop",
    "0x0032": "Bombchu Shop",
    "0x0033": "Happy Mask Shop",
    "0x0034": "Link's House",
    "0x0035": "Back Alley House (Dog Lady)",
    "0x0036": "Stable",
    "0x0037": "Impa's House",
    "0x0038": "Lakeside Laboratory",
    "0x0039": "Carpenters' Tent",
    "0x003a": "Gravekeeper's Hut",
    "0x003b": "Great Fairy's Fountain (Upgrades)",
    "0x003c": "Fairy's Fountain",
    "0x003d": "Great Fairy's Fountain (Spells)",
    "0x003e": "Grottos",
    "0x003f": "Grave (Redead)",
    "0x0040": "Grave (Fairy's Fountain)",
    "0x0041": "Royal Family's Tomb",
    "0x0042": "Shooting Gallery",
    "0x0043": "Temple of Time",
    "0x0044": "Chamber of the Sages",
    "0x0045": "Castle Hedge Maze (Day)",
    "0x0046": "Castle Hedge Maze (Night)",
    "0x0047": "Cutscene Map",
    "0x0048": "Dampé's Grave & Windmill",
    "0x0049": "Fishing Pond",
    "0x004a": "Castle Courtyard",
    "0x004b": "Bombchu Bowling Alley",
    "0x004c": "Ranch House & Silo",
    "0x004d": "Guard House",
    "0x004e": "Granny's Potion Shop",
    "0x004f": "Ganon's Tower Collapse & Battle Arena",
    "0x0050": "House of Skulltula",
    "0x0051": "Hyrule Field",
    "0x0052": "Kakariko Village",
    "0x0053": "Graveyard",
    "0x0054": "Zora's River",
    "0x0055": "Kokiri Forest",
    "0x0056": "Sacred Forest Meadow",
    "0x0057": "Lake Hylia",
    "0x0058": "Zora's Domain",
    "0x0059": "Zora's Fountain",
    "0x005a": "Gerudo Valley",
    "0x005b": "Lost Woods",
    "0x005c": "Desert Colossus",
    "0x005d": "Gerudo's Fortress",
    "0x005e": "Haunted Wasteland",
    "0x005f": "Hyrule Castle",
    "0x0060": "Death Mountain Trail",
    "0x0061": "Death Mountain Crater",
    "0x0062": "Goron City",
    "0x0063": "Lon Lon Ranch",
    "0x0064": "Ganon's Castle Exterior",
}

# Memory to string table for location in Majoras Mask
SCENE_DIC_MM = {
    "0x0000": "Southern Swamp (Clear)",
    "0x0001": "",
    "0x0002": "",
    "0x0003": "",
    "0x0004": "",
    "0x0005": "",
    "0x0006": "",
    "0x0007": "Grottos",
    "0x0008": "Cutscene Map",
    "0x0009": "",
    "0x000a": "Magic Hags' Potion Shop",
    "0x000b": "Majora's Lair",
    "0x000c": "Beneath the Graveyard",
    "0x000d": "Curiosity Shop",
    "0x000e": "",
    "0x000f": "",
    "0x0010": "Ranch House & Barn",
    "0x0011": "Honey & Darling's Shop",
    "0x0012": "Mayor's Residence",
    "0x0013": "Ikana Canyon",
    "0x0014": "Pirates' Fortress",
    "0x0015": "Milk Bar",
    "0x0016": "Stone Tower Temple",
    "0x0017": "Treasure Chest Shop",
    "0x0018": "Stone Tower Temple (Inverted)",
    "0x0019": "Clock Tower Rooftop",
    "0x001a": "Before the Portal to Termina",
    "0x001b": "Woodfall Temple",
    "0x001c": "Path to Mountain Village",
    "0x001d": "Ancient Castle of Ikana",
    "0x001e": "Deku Scrub Playground",
    "0x001f": "Odolwa's Lair",
    "0x0020": "Town Shooting Gallery",
    "0x0021": "Snowhead Temple",
    "0x0022": "Milk Road",
    "0x0023": "Pirates' Fortress Interior",
    "0x0024": "Swamp Shooting Gallery",
    "0x0025": "Pinnacle Rock",
    "0x0026": "Fairy's Fountain",
    "0x0027": "Swamp Spider House",
    "0x0028": "Oceanside Spider House",
    "0x0029": "Astral Observatory",
    "0x002a": "The Moon - Deku Trial",
    "0x002b": "Deku Palace",
    "0x002c": "Mountain Smithy",
    "0x002d": "Termina Field",
    "0x002e": "Post Office",
    "0x002f": "Marine Research Lab",
    "0x0030": "Dampé's House",
    "0x0031": "",
    "0x0032": "Goron Shrine",
    "0x0033": "Zora Hall",
    "0x0034": "Trading Post",
    "0x0035": "Romani Ranch",
    "0x0036": "Twinmold's Lair",
    "0x0037": "Great Bay Coast",
    "0x0038": "Zora Cape",
    "0x0039": "Lottery Shop",
    "0x003a": "",
    "0x003b": "Pirates' Fortress Exterior",
    "0x003c": "Fisherman's Hut",
    "0x003d": "Goron Shop",
    "0x003e": "Deku King's Chamber",
    "0x003f": "The Moon - Goron Trial",
    "0x0040": "Road to Southern Swamp",
    "0x0041": "Doggy Racetrack",
    "0x0042": "Cucco Shack",
    "0x0043": "Ikana Graveyard",
    "0x0044": "Goht's Lair",
    "0x0045": "Southern Swamp (Poisoned)",
    "0x0046": "Woodfall",
    "0x0047": "The Moon - Zora Trial",
    "0x0048": "Goron Village (Spring)",
    "0x0049": "Great Bay Temple",
    "0x004a": "Waterfall Rapids",
    "0x004b": "Beneath the Well",
    "0x004c": "Zora Hall Rooms",
    "0x004d": "Goron Village (Winter)",
    "0x004e": "Goron Graveyard",
    "0x004f": "Sakon's Hideout",
    "0x0050": "Mountain Village (Winter)",
    "0x0051": "Ghost Hut",
    "0x0052": "Deku Shrine",
    "0x0053": "Road to Ikana",
    "0x0054": "Swordsman's School",
    "0x0055": "Music Box House",
    "0x0056": "Igos du Ikana's Lair",
    "0x0057": "Tourist Information",
    "0x0058": "Stone Tower",
    "0x0059": "Stone Tower (Inverted)",
    "0x005a": "Mountain Village (Spring)",
    "0x005b": "Path to Snowhead",
    "0x005c": "Snowhead",
    "0x005d": "Path to Goron Village (Winter)",
    "0x005e": "Path to Goron Village (Spring)",
    "0x005f": "Gyorg's Lair",
    "0x0060": "Secret Shrine",
    "0x0061": "Stock Pot Inn",
    "0x0062": "Great Bay (Cutscene)",
    "0x0063": "Clock Tower Interior",
    "0x0064": "Woods of Mystery",
    "0x0065": "Lost Woods",
    "0x0066": "The Moon - Link Trial",
    "0x0067": "The Moon",
    "0x0068": "Bomb Shop",
    "0x0069": "Giants' Chamber",
    "0x006a": "Gorman Track",
    "0x006b": "Goron Racetrack",
    "0x006c": "East Clock Town",
    "0x006d": "West Clock Town",
    "0x006e": "North Clock Town",
    "0x006f": "South Clock Town",
    "0x0070": "Laundry Pool",
}
# Kokiri sword chest address: 800084B8
# Values closed: 000A
# value  opened: f5d5

# Midos House chest address: 80008598
# Values all closed: 000A
# Values for chest opening:  
    # Top left: 1FAF
    # Bottom left: 2A01
    # Top Right: 47F3
    # Bot Right: 77EF

#Ikana Valley Generic Grotto address: 80280C3C
#Chest closed: 000A
#Chest Opened: 00FE